# Generated by Django 3.2.8 on 2021-10-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0002_vacina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacina',
        ),
    ]
