# Generated by Django 3.2.8 on 2021-10-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0007_prioridades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Prioridades',
        ),
        migrations.DeleteModel(
            name='Vacina',
        ),
    ]
