# Generated by Django 3.2.8 on 2021-10-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0009_enfermeiro_gestores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gestores',
        ),
    ]
