# Generated by Django 3.2.8 on 2021-10-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0010_delete_gestores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=50)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_vacinacao.enfermeiro', verbose_name='Vacina')),
            ],
        ),
    ]
