# Generated by Django 3.2.8 on 2021-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0011_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='nome_paciente',
            field=models.CharField(max_length=50, verbose_name='Vacinado'),
        ),
    ]
