# Generated by Django 3.2.8 on 2021-10-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0012_alter_gestor_nome_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gestor',
        ),
    ]
