# Generated by Django 3.2.8 on 2021-10-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0014_pacientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='enfermeiro',
        ),
        migrations.DeleteModel(
            name='Enfermeiro',
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
    ]
