# Generated by Django 3.2.8 on 2021-10-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0016_pacientes_vacinas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pacientes',
        ),
        migrations.DeleteModel(
            name='Vacinas',
        ),
    ]
