# Generated by Django 3.2.8 on 2021-10-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0019_alter_enfermeiro_nome_vacina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enfermeiro',
        ),
    ]
