# Generated by Django 3.2.8 on 2021-10-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0021_enfermeiro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enfermeiro',
        ),
    ]
