# Generated by Django 3.2.8 on 2021-10-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0023_enfermeiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gestor', models.CharField(max_length=50)),
                ('nome_vacinados', models.CharField(max_length=50)),
            ],
        ),
    ]
