# Generated by Django 3.2.8 on 2021-10-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0024_gestor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gestor',
        ),
    ]
