# Generated by Django 3.2.8 on 2021-10-15 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacinacao', '0025_delete_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('nome_gestor', models.CharField(max_length=50)),
                ('nome_vacinados', models.CharField(max_length=50)),
                ('escolha_vacina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_vacinacao.enfermeiro')),
            ],
        ),
    ]
